Changed hooks

diff --git a/.githooks/pre-push b/.githooks/pre-push
--- a/.githooks/pre-push
+++ b/.githooks/pre-push
@@ -1,6 +1,7 @@
 #!/bin/sh
 
-echo -n "Running pre-push script"
+echo -en "\033[32mRunning pre-push script: \033[0m" >&2
+
 
 branch=$(git rev-parse --abbrev-ref HEAD)
 
@@ -8,24 +9,24 @@ if [ "$branch" = "main" ]; then
   tag=$(git tag --points-at HEAD)
 
   if [ -z "$tag" ]; then
-    echo -e ": \033[41mMaster branch commit requires a tag.\033[0m" >&2
+    echo -e "\033[41mMaster branch commit requires a tag.\033[0m" >&2
     exit 1
   elif ! echo "$tag" | grep -q '^v[0-9].*'; then
-    echo -e ": \033[41mTag format is invalid. It should start with 'v' followed by a number and any other characters.\033[0m" >&2
+    echo -e "\033[41mTag format is invalid. It should start with 'v' followed by a number and any other characters.\033[0m" >&2
     exit 1
   fi
+  echo "Tag is valid."
 
-  echo ": Tag is valid."
-
-  echo "Are you sure to push to $branch with tag $tag? (y/n)"
-  read -r answer
+  echo -n "Are you sure to push to $branch with tag $tag? (y/n) "
+  read -n 1 -r < /dev/tty
+  echo
   
-  if [ "$answer" != "y" ]; then
-    echo "Aborting push."
+  if [[ ! $REPLY =~ ^[Yy]$ ]]; then
+    echo "Aborting push"
     exit 1
   fi
 
-  echo "Pushing to $branch with tag $tag."
+  echo "Pushing tags"
   git push --tags --no-verify
 
 fi
